### ISSUE TITLE
Can you provide this file.

### ISSUE THREAD

**Issue by victorvondoom25** [hnhparitosh/Matsya#2]
![image](https://github.com/user-attachments/assets/26a9b3ca-eb18-455d-8d16-4272020d9c41)

data/chessdata_500k.csv

**Comment by hnhparitosh** [comment]
hi, I got the data from [this Kaggle dataset](https://www.kaggle.com/datasets/ronakbadhe/chess-evaluations) and probably took 500k rows from the complete dataset.
